stage('Build Docker Image') {
    steps {
        dir('akash-hotels') {
            sh 'docker build -t akazz0/akash-hotels:1.0 .'
        }
    }
}

stage('Push Docker Image') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'dockerhub-credentials',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_TOKEN'
            )
        ]) {
            sh '''
                echo "$DOCKER_TOKEN" | docker login \
                    -u "$DOCKER_USER" \
                    --password-stdin

                docker push akazz0/akash-hotels:1.0
            '''
        }
    }
}