pipeline {
    agent any

    stages {

        stage('Test Docker') {
            steps {
                sh 'docker --version'
                sh 'docker ps'
            }
        }

        stage('Build Application') {
            steps {
                dir('akash-hotels') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('akash-hotels') {
                    sh 'docker build -t akash-hotels:jenkins .'
                }
            }
        }
    }
}